#!/usr/bin/python

# Prefix Fields
PREFIX_NAME = 0
PREFIX_SYMBOL = 1
PREFIX_FACTOR = 2
PREFIX_VALUE = 3

# Unit Fields
UNIT_NAME = 0
UNIT_TYPE = 1
UNIT_SYMBOL = 2
UNIT_EQUATION_SYMBOL = 3
UNIT_BASE_NUMER = 4
UNIT_BASE_DENOM = 5
UNIT_IMPL_NUMER = 6
UNIT_IMPL_DENOM = 7
UNIT_DESC = 8